include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.config.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
