name: dicoding_expert
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_analytics: ^9.2.0
  firebase_core: ^1.19.2
  firebase_crashlytics: ^2.8.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  json_serializable: ^6.3.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  hive_generator: ^1.1.3
  http_mock_adapter: ^0.3.3
  injectable_generator: ^1.5.3
  mockito: ^5.2.0

flutter:
  uses-material-design: true
  assets:
    - certificates/
  #   - images/a_dot_ham.jpeg
